# Generated by Django 3.1.7 on 2021-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211021_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='branch',
            field=models.CharField(choices=[('Heliopolis', 'Heliopolis'), ('Maadi', 'Maadi')], max_length=120),
        ),
    ]
