# Generated by Django 3.1.7 on 2021-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210904_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('branch', models.CharField(choices=[('Heliopolis', 'Heliopolis'), ('5th-settelment', '5th settelment')], max_length=120)),
            ],
        ),
    ]
